name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: ['8.1']
        experimental: [false]

        include:
          - php: '8.2'
            experimental: true

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL, display_errors=On
          coverage: none
          tools: composer

      - name: Install dependencies - normal
        if: ${{ matrix.php < 8.2 }}
        run: |
          composer install --prefer-dist --no-progress --no-interaction

      - name: Install dependencies - ignore platform reqs
        if: ${{ matrix.php >= 8.2 }}
        run: |
          composer update --prefer-dist --no-progress --ignore-platform-reqs --no-interaction

      - name: Execute Unit Tests
        run: vendor/bin/phpunit
